"""
Assemble source/sink files for SCHISM model
"""

import os
import numpy as np
import json
import shutil
from pathlib import Path

from .NWM.gen_sourcesink_nwm import gen_sourcesink_nwm
from .Constant_sinks.set_constant_sink import set_constant_sink
from .Relocate.relocate_source_feeder import relocate_sources2
from .Replace_with_USGS.replace_with_obs import source_nwm2usgs
from .Replace_with_USGS.source_temperature import (
    replace_source_temperatures_with_usgs,
)
from .Patch_artificial_island.patch_artificial_island_source_sink import (
    apply_artificial_island_corrections,
    zero_artificial_island_sources_after_replace_USGS_before_relocation,
)
from .Spatial_corrections.region_zeroing import zero_configured_source_regions
from .workflow_constants import NWM_ECGC_SHAPEFILE
from ...utils.utils import mkcd_new_dir, STOFS3D_ATL_STATES
from ...utils.projection import project_geodataframe
from pylib_experimental.schism_file import source_sink, TimeHistory


script_path = os.path.dirname(os.path.realpath(__file__))


def gen_relocated_source(original_source_sink_dir, relocated_source_sink_dir):
    """
    Generate relocated vsource.th for STOFS-3D-ATL
    based on sources.json and sinks.json generated by relocate_sources2
    """

    original_ss = source_sink.from_files(source_dir=original_source_sink_dir)

    original_ele_nwm_mapping = json.load(
        open(f'{original_source_sink_dir}/sources.json', 'r')
    )
    # reverse the mapping
    original_nwm_ele_mappping = {}
    potential_duplicates = {}
    for ele, nwm_fids in original_ele_nwm_mapping.items():

        if len(nwm_fids) > 1:
            print(
                f'Warning: original source element {ele} is mapped to multiple NWM feature IDs: {nwm_fids}. '
                'This can happen if multiple NWM segments intersect with the same element. '
                'In this case, there is likely only one large river'
            )
            print(f'mean flow of ele {ele} (no-feeder mesh): {original_ss.vsource.df[ele].values.mean()}')
            potential_duplicates[ele] = original_ss.vsource.df[ele].values.mean()
        for nwm_fid in nwm_fids:
            if nwm_fid in original_nwm_ele_mappping:
                print(
                    f"Warning: NWM feature ID {nwm_fid} is already mapped to "
                    f"{original_nwm_ele_mappping[nwm_fid]}. Overwriting with {ele}"
                )  # if an nwm_fid is mapped to multiple elements, keep the last one.

                # This can happen if the original source_sink is generated by pyschism,
                # with an NWM segment weaving in and out of multiple elements,
                # resulting in multiple sources and sinks maped to the same nwm_fid.
                # However, the relocation process will ignore all sinks, so only one source
                # should be mapped to the same nwm_fid. And the exact location is somewhat arbitrary.
                # In a rare case, a river can go in as one nwm_fid and out as another nwm_fid,
                # so make sure this doesn't happen by properly aligning the schism land boundary
                # and avoid NWM segments weaving in and out of multiple elements.
            original_nwm_ele_mappping[nwm_fid] = ele

    relocated_ele_nwm_mapping = json.load(
        open(f'{relocated_source_sink_dir}/sources.json', 'r')
    )

    relocated_ele_mapping = {}
    seen_original_eles = set()
    for ele, nwm_fids in relocated_ele_nwm_mapping.items():
        if nwm_fids == []:
            raise ValueError(f'Relocated source element {ele} has no NWM feature IDs!')
        relocated_ele_mapping[ele] = []
        for nwm_fid in nwm_fids:
            if nwm_fid not in original_nwm_ele_mappping:
                raise ValueError(f'Relocated source element {ele} has NWM fid {nwm_fid} '
                                 'not found in original source elements!')
            # when an original ele corresponds to multiple NWM fids, relocated_ele_mapping[ele] may have duplicates
            # , so we remove duplicates here
            target_original_ele = original_nwm_ele_mappping[nwm_fid]
            if target_original_ele not in seen_original_eles:
                relocated_ele_mapping[ele].append(target_original_ele)
                seen_original_eles.add(target_original_ele)

    # double check that each original source element is mapped to only one relocated source element
    seen = set()
    for eles in relocated_ele_mapping.values():
        for ele in eles:
            if ele in seen:
                raise ValueError(
                    f"Original source element {ele} is mapped to multiple relocated source elements"
                )
            seen.add(ele)

    vsource_data = np.zeros((original_ss.vsource.n_time, len(relocated_ele_mapping)), dtype=float)
    for i, [relocated_ele, original_eles] in enumerate(relocated_ele_mapping.items()):
        for original_ele in original_eles:
            vsource_data[:, i] += original_ss.vsource.df[original_ele].values

    # assemble relocated vsource.th and msource.th
    relocated_vsource = TimeHistory(
        data_array=np.c_[original_ss.vsource.time, vsource_data], columns=list(relocated_ele_mapping.keys())
    )

    relocated_msource_data = np.ones((original_ss.vsource.n_time, len(relocated_ele_mapping)), dtype=float)
    relocated_msource_list = [
        TimeHistory(
            data_array=np.c_[original_ss.vsource.time, relocated_msource_data*-9999],
            columns=list(relocated_ele_mapping.keys())
        ),  # Temperature
        TimeHistory(
            data_array=np.c_[original_ss.vsource.time, relocated_msource_data*0],
            columns=list(relocated_ele_mapping.keys())
        )  # Salinity
    ]

    return relocated_vsource, relocated_msource_list


def _generate_original_source_sink(config, model_input_path, wdir):
    """Generate NWM sources/sinks and update the resolved NWM cache path."""
    original_source_sink_dir = f'{wdir}/original_source_sink/'
    mkcd_new_dir(original_source_sink_dir)
    source_grid = (
        config.hgrid_without_feeders
        if config.hgrid_without_feeders is not None
        else f'{model_input_path}/hgrid.gr3'
    )
    os.symlink(str(source_grid), 'hgrid.gr3')

    if config.existing_source_json_path is not None:
        print('reusing existing sources.json and sinks.json ...')
        for filename in ('sources.json', 'sinks.json'):
            existing_file = Path(config.existing_source_json_path) / filename
            if existing_file.exists():
                os.system(f'cp -rf {existing_file} .')
            else:
                print(
                    f'Warning: specified {existing_file} does not exist, '
                    'generating it from scratch ...'
                )

    actual_nwm_cache_folder = gen_sourcesink_nwm(
        hgrid_fname='./hgrid.gr3',
        startdate=config.startdate,
        rnday=config.rnday,
        cache_folder=config.nwm_cache_folder,
    )

    if config.nwm_cache_folder is None:
        config.nwm_cache_folder = actual_nwm_cache_folder
        print(f'Setting config.nwm_cache_folder to {actual_nwm_cache_folder}')
    elif Path(actual_nwm_cache_folder).resolve(strict=True) != Path(
        config.nwm_cache_folder
    ).resolve(strict=True):
        print(
            f'Warning: the actual nwm_cache_folder has been generated at '
            f'{actual_nwm_cache_folder}, different from the specified '
            f'config.nwm_cache_folder {config.nwm_cache_folder}, '
            'make sure this is intended!'
        )
        config.nwm_cache_folder = actual_nwm_cache_folder


def _describe_source_grid(config):
    """Report whether the main grid is expected to contain feeder elements."""
    if config.hgrid_without_feeders is not None:
        print(
            'Normal case: beside the main hgrid, '
            f'an hgrid without feeders is provided: '
            f'{config.hgrid_without_feeders}, assuming the main hgrid has '
            'feeders!'
        )
        return True

    print(
        'Special case: only the main hgrid is provided. '
        'Caution: you should not search for NWM source/sink on a grid with '
        'feeders! I will assume the main hgrid has no feeders and carry on.'
    )
    return False


def _replace_nwm_flow_with_usgs(config, model_input_path, wdir):
    """Adjust NWM source flows using USGS observations."""
    print('replacing NWM sources with USGS observed flow rates ...')
    source_nwm2usgs(
        start_time_str=config.startdate.strftime('%Y-%m-%d %H:%M:%S'),
        states=STOFS3D_ATL_STATES,
        f_shapefile=NWM_ECGC_SHAPEFILE,
        original_ss_dir=f'{wdir}/original_source_sink/',
        nwm_data_dir=config.nwm_cache_folder,
        output_dir=f'{wdir}/USGS_adjusted_sources/',
        usgs_cache_folder=(
            config.usgs_cache_folder
            if config.usgs_cache_folder is not None
            else Path(model_input_path) / 'USGS_cache'
        ),
    )


def _suppress_island_sources_before_relocation(
    config, model_input_path, wdir, artificial_island_info
):
    """Apply island-specific pre-relocation flow suppression."""
    zero_artificial_island_sources_after_replace_USGS_before_relocation(
        source_sink_dir=f'{wdir}/original_source_sink/',
        hgrid_file=(
            config.hgrid_without_feeders
            if config.hgrid_without_feeders is not None
            else f'{model_input_path}/hgrid.gr3'
        ),
        patch_info_file=artificial_island_info,
        output_dir=(
            f'{wdir}/zeroed_sources_after_replace_USGS_before_relocation/'
        ),
    )


def _read_original_source_sink(wdir):
    """Read the generated source/sink directly, without relocation."""
    return source_sink.from_files(f'{wdir}/original_source_sink/')


def _relocate_source_sink(config, model_input_path, wdir, main_hgrid_has_feeder):
    """Relocate sources and assemble the relocated base source/sink object."""
    relocated_source_sink_dir = f'{wdir}/relocated_source_sink/'
    mkcd_new_dir(relocated_source_sink_dir)
    os.symlink(f'{model_input_path}/hgrid.gr3', 'hgrid.gr3')
    relocate_sources2(
        old_ss_dir=f'{wdir}/original_source_sink/',
        feeder_info_file=config.feeder_info_file,
        hgrid_fname=f'{model_input_path}/hgrid.gr3',
        outdir=relocated_source_sink_dir,
        max_search_radius=2100,
        mandatory_sources_coor=config.mandatory_sources_coor,
        allow_neglection=False,
        main_hgrid_has_feeder=main_hgrid_has_feeder,
    )

    if config.reuse_source_json:
        os.system(f'ln -sf {wdir}/original_source_sink/sinks.json .')
        gen_sourcesink_nwm(
            hgrid_fname=f'{model_input_path}/hgrid.gr3',
            startdate=config.startdate,
            rnday=config.rnday,
            cache_folder=config.nwm_cache_folder,
        )
        relocated_ss = source_sink.from_files(
            source_dir=relocated_source_sink_dir,
        )
        return source_sink(
            vsource=relocated_ss.vsource,
            vsink=None,
            msource=relocated_ss.msource,
        )

    relocated_vsource, relocated_msource_list = gen_relocated_source(
        original_source_sink_dir=f'{wdir}/original_source_sink/',
        relocated_source_sink_dir=relocated_source_sink_dir,
    )
    base_ss = source_sink(
        vsource=relocated_vsource,
        vsink=None,
        msource=relocated_msource_list,
    )
    base_ss.writer(relocated_source_sink_dir)
    return base_ss


def _resolve_usgs_cache_folder(config, model_input_path):
    """Return the configured USGS cache or the model-input default."""
    return (
        config.usgs_cache_folder
        if config.usgs_cache_folder is not None
        else Path(model_input_path) / 'USGS_cache'
    )


def _replace_source_temperatures(base_ss, config, hgrid, model_input_path, wdir):
    """Apply configured USGS temperature replacement to source elements."""
    source_mapping_dir = (
        f'{wdir}/relocated_source_sink/'
        if config.relocate_source
        else f'{wdir}/original_source_sink/'
    )
    base_ss, replaced_count = replace_source_temperatures_with_usgs(
        base_ss=base_ss,
        hgrid=hgrid,
        source_mapping_dir=source_mapping_dir,
        start_time=config.startdate,
        usgs_cache_folder=_resolve_usgs_cache_folder(
            config, model_input_path
        ),
        nwm_shapefile=NWM_ECGC_SHAPEFILE,
        states=STOFS3D_ATL_STATES,
        diagnostics_dir=Path(wdir) / 'source_temperature',
        pooling=config.source_temperature_pooling,
        nwm_data_dir=config.nwm_cache_folder,
    )
    print(f'[SOURCE TEMPERATURE] replaced {replaced_count} source(s).')
    return base_ss


def _zero_configured_source_regions(base_ss, config, hgrid):
    """Apply optional final source-region zeroing from its stage config."""
    base_ss, zeroed_count = zero_configured_source_regions(
        base_ss=base_ss,
        hgrid=hgrid,
        correction_info=config.zero_source_region_info,
    )
    print(f'[SOURCE REGIONS] zeroed {zeroed_count} unique source(s).')
    return base_ss


def _apply_artificial_island_patch(
    base_ss, config, hgrid, model_input_path, wdir, patch_info_file
):
    """Apply configured artificial-island source/sink corrections."""
    patch_output_dir = f'{wdir}/patch_artificial_island_source_sink/'
    mkcd_new_dir(patch_output_dir)
    os.symlink(f'{model_input_path}/hgrid.gr3', 'hgrid.gr3')
    return apply_artificial_island_corrections(
        base_ss=base_ss,
        hgrid=hgrid,
        original_source_sink_dir=f'{wdir}/original_source_sink/',
        patch_info_file=patch_info_file,
        start_time=config.startdate,
        usgs_cache_folder=_resolve_usgs_cache_folder(
            config, model_input_path
        ),
        output_dir=patch_output_dir,
    )


def _generate_constant_sink_source_sink(config, hgrid, wdir):
    """Generate background and pump sink contributions."""
    constant_sink_dir = f'{wdir}/constant_sink/'
    mkcd_new_dir(constant_sink_dir)

    constant_sink_shapefile = getattr(config, 'constant_sink_shapefile', None)
    if constant_sink_shapefile is None:
        constant_sink_shapefile = (
            Path(script_path)
            / 'Constant_sinks'
            / 'levee_pump_polys_2026_with_poly_type.shp'
        )
    else:
        constant_sink_shapefile = Path(constant_sink_shapefile)

    exclude_shapefile = getattr(
        config, 'exclude_constant_sink_shapefile', None
    )
    if exclude_shapefile is None:
        exclude_shapefile = (
            Path(script_path)
            / 'Constant_sinks'
            / 'exclude_constant_sink_at_savannah_charleston.shp'
        )
    else:
        exclude_shapefile = Path(exclude_shapefile)

    for shapefile in (constant_sink_shapefile, exclude_shapefile):
        for component in shapefile.parent.glob(f'{shapefile.stem}.*'):
            shutil.copy2(component, '.')

    return set_constant_sink(
        wdir=constant_sink_dir,
        shapefile_name=constant_sink_shapefile.name,
        hgrid=hgrid,
        exclude_constant_sink_shapefile=exclude_shapefile.name,
    )


def _write_source_sink_diagnostics(total_ss, hgrid, wdir):
    """Write mean source and sink coordinates/flows for inspection."""
    hgrid.compute_ctr()
    source_indices = np.asarray(total_ss.source_eles) - 1
    source_diagnostics = np.column_stack((
        np.asarray(hgrid.xctr)[source_indices],
        np.asarray(hgrid.yctr)[source_indices],
        total_ss.vsource.df.values.mean(axis=0),
    ))
    np.savetxt(
        f'{wdir}/vsource.xyz',
        source_diagnostics,
        fmt='%.6f',
        header='lon lat vsource',
        comments='',
    )

    sink_indices = np.asarray(total_ss.sink_eles) - 1
    sink_diagnostics = np.column_stack((
        np.asarray(hgrid.xctr)[sink_indices],
        np.asarray(hgrid.yctr)[sink_indices],
        total_ss.vsink.df.values.mean(axis=0),
    ))
    np.savetxt(
        f'{wdir}/vsink.xyz',
        sink_diagnostics,
        fmt='%.6f',
        header='lon lat vsink',
        comments='',
    )


def _write_final_source_sink(total_ss, config, hgrid, wdir):
    """Write assembled source/sink forcing and diagnostics."""
    total_ss.writer(f'{wdir}/')

    os.chdir(f'{wdir}')
    source_json_dir = (
        'relocated_source_sink'
        if config.relocate_source
        else 'original_source_sink'
    )
    os.system(f'ln -sf ./{source_json_dir}/sources.json .')

    if config.source_ele_replace_dict:
        from .Relocate.patch_feeder_source_sink_in import (
            replace_ele_in_source_sink,
        )

        replace_ele_in_source_sink(wdir, config.source_ele_replace_dict)

    _write_source_sink_diagnostics(total_ss, hgrid, wdir)


def assemble_source_sink(config, hgrid, model_input_path=None, wdir=None):
    """
    Assemble source/sink files for SCHISM model
    The assembled source/sink files include:
        vsource.th, vsink.th, msource.th, source_sink.in, source.nc,
        sources.json, sinks.json
    """

    main_hgrid_has_feeder = _describe_source_grid(config)
    artificial_island_info = config.artificial_island_source_sink_info

    _generate_original_source_sink(config, model_input_path, wdir)

    if config.replace_nwm_with_usgs:
        _replace_nwm_flow_with_usgs(config, model_input_path, wdir)

    if artificial_island_info is not None:
        _suppress_island_sources_before_relocation(config, model_input_path, wdir, artificial_island_info)

    if config.relocate_source:
        base_ss = _relocate_source_sink(
            config=config, model_input_path=model_input_path, wdir=wdir,
            main_hgrid_has_feeder=main_hgrid_has_feeder,
        )
    else:
        base_ss = _read_original_source_sink(wdir)

    if config.replace_source_temperature_with_usgs:
        base_ss = _replace_source_temperatures(base_ss, config, hgrid, model_input_path, wdir)

    if config.zero_configured_source_regions:
        base_ss = _zero_configured_source_regions(base_ss, config, hgrid)

    if artificial_island_info is not None:
        base_ss = _apply_artificial_island_patch(base_ss, config, hgrid, model_input_path, wdir, artificial_island_info)

    background_ss = _generate_constant_sink_source_sink(config=config, hgrid=hgrid, wdir=wdir)

    total_ss = base_ss + background_ss

    _write_final_source_sink(total_ss=total_ss, config=config, hgrid=hgrid, wdir=wdir)


def sample2():
    '''
    Subsetting example workflow for STOFS3D Atlantic v7.2,
    assuming the original source_sink files have already
    been generated by gen_sourcesink_nwm
    '''
    from datetime import datetime
    from .Relocate.relocate_source_feeder import (
        v19p2_for_sms_v27_mandatory_sources_coor, relocate_sources2
    )
    import geopandas as gpd
    from shapely import get_coordinates
    from pylib import schism_grid as schism_read
    from pylib_experimental.schism_file import source_sink

    # --------------inputs -----------------
    wdir = '/sciclone/schism10/feiye/TEMP/clip_by_polygon/I03/Source_sink/'
    main_hgrid_fname = f'{wdir}/hgrid.gr3'
    # hgrid_without_feeders_fname = main_hgrid_fname

    startdate = datetime(2018, 8, 30)
    rnday = 10

    region_gdf = project_geodataframe(
        gpd.read_file(
            '/sciclone/schism10/feiye/TEMP/clip_by_polygon/hires/hires_buffered.shp'
        ),
        'EPSG:4326',
        "source/sink region projection",
    )
    # -------------------- end inputs -----------------

    os.chdir(wdir)
    region_list = [get_coordinates(p) for p in region_gdf.explode(index_parts=True).exterior]

    # generate original source_sink files
    # use hgrid_without_feeders (if available) to generate original source_sink files
    # if hgrid_without_feeders is not available, use the main hgrid directly
    # For this sample, the main hgrid is used directly.
    # os.makedirs(f'{wdir}/original_source_sink/', exist_ok=True)
    # os.chdir(f'{wdir}/original_source_sink/')
    # os.system(f'ln -sf {main_hgrid_fname} hgrid.gr3')
    # cache_folder = gen_sourcesink_nwm(
    #     hgrid_fname=hgrid_without_feeders_fname,
    #     startdate=startdate, rnday=rnday,
    #     cache_folder=None,
    # )

    print('read original source/sink')
    original_ss = source_sink.from_files(source_dir=f'{wdir}/original_source_sink/')

    print('subsetting original source/sink by polygons')
    inside_ss, outside_ss = original_ss.clip_by_polygons(
        hgrid=schism_read(f'{wdir}/original_source_sink/hgrid.gr3'),  # can also use pylib's read()
        polygons_xy=region_list
    )
    inside_ss.writer(f'{wdir}/inside_source_sink/')
    os.system(f'ln -sf {main_hgrid_fname} {wdir}/inside_source_sink/hgrid.gr3')
    outside_ss.writer(f'{wdir}/outside_source_sink/')
    os.system(f'ln -sf {main_hgrid_fname} {wdir}/outside_source_sink/hgrid.gr3')

    # relocate sources in high-res regions (inside_ss) on the main hgrid
    # subset sources.json and sinks.json in the high-res regions based on the original source_sink files
    for i, json_file in enumerate(['sources.json', 'sinks.json']):
        original_ele2nwm_fid = json.load(open(
            f'{wdir}/original_source_sink/{json_file}', 'r', encoding='utf-8'
        ))
        ele2nwm_fid = {
            str(int(k)): v for k, v in original_ele2nwm_fid.items()
            if int(k) in inside_ss.source_sink_in.ip_group[i]
        }
        with open(f'{wdir}/inside_source_sink/{json_file}', 'w', encoding='utf-8') as f:
            json.dump(ele2nwm_fid, f, indent=4)

    print('generate sources.json for relocated sources on the main hgrid')
    relocate_sources2(
        old_ss_dir=f'{wdir}/inside_source_sink/',
        feeder_info_file='/sciclone/schism10/Hgrid_projects/STOFS3D-v8/v31/Feeder/feeder_heads_bases.xy',
        hgrid_fname=main_hgrid_fname, outdir=f'{wdir}/relocated_source_sink/',
        max_search_radius=2100, mandatory_sources_coor=v19p2_for_sms_v27_mandatory_sources_coor,
        allow_neglection=True, region_list=region_list
    )

    print('generate relocated source/sink')
    os.chdir(f'{wdir}/relocated_source_sink/')
    os.system(f'ln -sf {wdir}/inside_source_sink/sinks.json .')
    gen_sourcesink_nwm(  # with existing sources.json and sinks.json
        hgrid_fname=main_hgrid_fname,
        startdate=startdate, rnday=rnday,
        cache_folder='/sciclone/schism10/feiye/TEMP/clip_by_polygon/I03/Source_sink/original_source_sink/20180830',
        # cache_folder generated by the first call
    )

    print('read relocated source/sink and discard sinks')
    relocated_ss = source_sink.from_files(  # strictly check on duplicates since there should not be any
        source_dir=f'{wdir}/relocated_source_sink/', strict_check=True
    )  # sinks will be discarded later, only sources will be used

    # discard sinks from relocated_ss by setting vsink=None
    relocated_ss = source_sink(
        vsource=relocated_ss.vsource, vsink=None, msource=relocated_ss.msource
    )

    print('combine source/sinks inside and outside the high-res regions')
    combined_ss = outside_ss + relocated_ss
    combined_ss.writer(f'{wdir}/combined_source_sink/')

    print('Done!')


if __name__ == "__main__":
    sample2()
    print('Done!')
