name: stofs3d_v7p2_original
workdir: ./
input_grid: hgrid.ll
output_grid: hgrid.ll.dem_loaded.mpi.gr3
dem_dir: /sciclone/schism10/Hgrid_projects/DEMs/npz2
reverse_sign: true
copy_provenance: true
sources:
  - name: original_patched
    dem_json: DEM_info_original_patched.json
merge_rules: []
