name: stofs3d_v7
workdir: /sciclone/schism10/feiye/STOFS3D-v8/I13b/Bathy_edit/DEM_loading
input_grid: hgrid.ll
output_grid: hgrid.ll.dem_loaded.mpi.gr3
dem_dir: /sciclone/schism10/Hgrid_projects/DEMs/npz2
reverse_sign: true
copy_provenance: true
sources:
  - name: original
    dem_json: DEM_info_original.json
  - name: bluetopo
    dem_json: DEM_info_with_bluetopo.json
merge_rules:
  - name: deeper_louisiana_bluetopo_region
    method: max_depth
    sources: [original, bluetopo]
    region: v18_s2_v1_polys_dissolved.shp
