[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stofs3d-setup"
version = "0.1.1"
requires-python = ">=3.10"

dependencies = [
    "pydantic>=2",
    "pyyaml>=6",
    "fiona",
    "gsw",
    "pyschism @ git+https://github.com/schism-dev/pyschism.git@v0.1.17",
    "pyshp",
    "pylibs-ocean",
]

[project.scripts]
stofs3d-setup = "stofs3d_setup.cli:app"
stofs3d-hgrid-preproc = "stofs3d_setup.ops.Grid.hgrid_preproc.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
