#!/bin/bash --login

##New Hercules-2 nodes
#SBATCH -D .
#SBATCH -J 40g
#SBATCH --partition=hercules-2
##SBATCH --reservation=hercules_exp
##SBATCH --qos=windfall
##80 cores/node
#SBATCH -N 35
#SBATCH -n 2800
#SBATCH --exclusive
#SBATCH -t 08:00:00  
#SBATCH -o myout
#SBATCH -e err2.out
#SBATCH --mail-user=yjzhang@vims.edu
#SBATCH --mail-type=all  #send email for start, end and fail

set -e
ulimit -s unlimited 

source /home/yjzhang/modules.hercules

#Ufuk suggested the following to avoid hang on large jobs
#export FI_MLX_INJECT_LIMIT=0

srun ./pschism_HERCULES_NO_PARMETIS_PREC_EVAP_BLD_STANDALONE_SH_MEM_COMM_TVD-VL 6
