#!/bin/bash
#SBATCH --job-name=CORIE
#SBATCH --partition=compute
#SBATCH --nodes=1
##128cores/node
#SBATCH --ntasks-per-node=108
#SBATCH --exclusive
##Compute partitin up to 8 hrs
#SBATCH --time=00:40:00
#SBATCH --mail-type=NONE
#SBATCH --account=gg0028
#SBATCH --output=my_job.%j.out

# limit stacksize ... adjust to your programs need
# and core file size - try not to use unlimit
ulimit -s 132400
#ulimit -s unlimited
ulimit -c 0

#module load intel-oneapi-compilers openmpi/4.1.2-intel-2021.5.0
#module load netcdf-c/4.8.1-openmpi-4.1.2-intel-2021.5.0
#module load netcdf-fortran/4.5.3-openmpi-4.1.2-intel-2021.5.0
source /home/g/g260135/gcc_tool

export OMPI_MCA_pml="ucx"
export OMPI_MCA_btl=self
export OMPI_MCA_osc="pt2pt"
export UCX_IB_ADDR_TYPE=ib_global
# for most runs one may or may not want to disable HCOLL
export OMPI_MCA_coll="^ml,hcoll"
export OMPI_MCA_coll_hcoll_enable="0"
export HCOLL_ENABLE_MCAST_ALL="0"
export HCOLL_MAIN_IB=mlx5_0:1
export UCX_NET_DEVICES=mlx5_0:1
export UCX_TLS=mm,knem,cma,dc_mlx5,dc_x,self
export UCX_UNIFIED_MODE=y
export HDF5_USE_FILE_LOCKING=FALSE
export OMPI_MCA_io="romio321"
export UCX_HANDLE_ERRORS=bt


# Use srun (not mpirun or mpiexec) command to launch
# programs compiled with any MPI library
srun -l --cpu_bind=verbose --hint=nomultithread \
  --distribution=block:cyclic ./pschism_levante_VL 8
