#!/bin/bash  
#SBATCH -J R210g  
#SBATCH -A XXX
##queues: 'windfall' max 450 nodes (no walltime limit but lower priority)
#SBATCH -q windfall
#SBATCH --partition=orion
#SBATCH -N 10
#SBATCH -n 400
#SBATCH -t 10:00:00  
#SBATCH --exclusive
#SBATCH -o myout
#SBATCH -e err2.out
#SBATCH --mail-user=yjzhang@vims.edu
#SBATCH --mail-type=ALL  #send email for start, end and fail

module load 

srun ./pschism_
