profile: "v7.4_2017"   # *

run:
  project_dir: "/sciclone/schism10/hjyoo/task/task10_Atlantic/stofs3d-setup_v7p4/"
  runid: "102a"
  hgrid_path: "/sciclone/schism10/hjyoo/task/task10_Atlantic/stofs3d-setup_v7p4/hgrid_input/hgrid_RUN102a.gr3"

model:
  version: "v7p4"
  rnday: 396
  startdate: "2016-12-01"  # *
  replace_nwm_with_usgs: true
  replace_source_temperature_with_usgs: true
  nwm_cache_folder: "/sciclone/schism10/feiye/STOFS3D-v8/NWM/CONUS/netcdf/CHRTOUT/for_2017_hindcast/"  # Use null or omit if the NWM cache is unavailable
  existing_source_json_path: null

runtime:
  scr_dir: null  # Use null if outputs should not be saved on scratch

inputs:
  bctides: true
  vgrid: true
  gr3: true
  nudge_gr3: true
  shapiro: true
  diffmin: true
  drag: true
  elev_ic: false
  flux_th: false
  source_sink: true
  soil: false
  watertype: true
  "hotstart.nc": false
  "3D.th.nc": false
  "*nu.nc": false
  "elev2D.th.nc": false
  "*.prop": true
