profile: "v7.4_2017"   # *

run:
  project_dir: "/sciclone/schism10/feiye/STOFS3D-v7.4/"
  runid: "100x"  # *
  hgrid_path: "/sciclone/schism10/Hgrid_projects/STOFS3D-v7.4/v32/v32b.gr3"

model:
  version: "v7p4"
  rnday: 3
  startdate: "2016-12-01"  # *
  replace_nwm_with_usgs: True
  nwm_cache_folder: '/sciclone/schism10/feiye/STOFS3D-v8/NWM/CONUS/netcdf/CHRTOUT/for_2017_hindcast/'  # Use None or delete this line if you don't have saved NWM product
  existing_source_json_path: '/sciclone/schism10/feiye/STOFS3D-v7.4/I01/saved_source_sink_json/'  # Use None or delete this line if you don't have existing files holding the mapping between schism elements and NWM segments


runtime:
  scr_dir: "/sciclone/scr10/feiye/STOFS3D-v7.4/"  # Use None if you don't want to save the outputs on a scratch disk.

inputs:
  bctides: false
  vgrid: false
  gr3: true
  nudge_gr3: false
  shapiro: true
  diffmin: true
  drag: true
  elev_ic: false
  flux_th: false
  source_sink: false
  soil: false
  "hotstart.nc": false
  "3D.th.nc": false
  "*nu.nc": false
  "elev2D.th.nc": false
  "*.prop": false
