!     This script is convert ncl binary into vsource.th     
!     Recommend to use intel ifort
!     ifort -o cvt2th cvt2th.f90
!     Input: dim.dat, vsource.bin (generated by ncl)
!     Output: vsource.th
      real,allocatable :: vsource(:)

      open(10,file='dim.dat')
      read(10,*) np
      read(10,*) nt
      close(10)
      allocate(vsource(np))

      open(11,file='vsource.bin',form='unformatted')
      open(21,file='vsource.th',status='replace')


      do l=1,nt
         read(11) vsource
         write(21,99) (l-1)*3600.,vsource(:)
      end do

      deallocate(vsource)
 99   format(f9.0,<np>(f8.3)) !<np> only work for intel compiler

      end
