!$Id: gotm-f2pywrappers2.F90,v 1.2 2007-01-19 09:40:25 jorn Exp $

!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2_2236)
!     It contains Fortran 90 wrappers to fortran functions.

subroutine f2pyinitgotm(f2pysetupfunc)

    use gotm, only : init_gotm,time_loop,clean_up

    interface
        subroutine f2pysetupfunc(init_gotm,time_loop,clean_up)
            external init_gotm,time_loop,clean_up
        end subroutine f2pysetupfunc
    end interface

    call f2pysetupfunc(init_gotm,time_loop,clean_up)

end subroutine f2pyinitgotm


subroutine f2pyinittime(f2pysetupfunc)

    use time, only : maxn
    use time, only : minn

    interface
        subroutine f2pysetupfunc(maxn,minn)
            integer :: maxn,minn
        end subroutine f2pysetupfunc
    end interface

    call f2pysetupfunc(maxn,minn)

end subroutine f2pyinittime


subroutine f2pyinitgui_util(f2pysetupfunc)

    use gui_util, only : redirectoutput,resetoutput,getversion

    interface
        subroutine f2pysetupfunc(redirectoutput,resetoutput,getversion)
            external redirectoutput,resetoutput,getversion
        end subroutine f2pysetupfunc
    end interface

    call f2pysetupfunc(redirectoutput,resetoutput,getversion)

end subroutine f2pyinitgui_util
