{% set name = "pschism" %}
{% set version = "5.10.1" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}      #-{{ TVD_LIM|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/schism-dev/schism.git
  git_tag: v5.10

build:
  number: {{ build }}
  skip: true #[win]
  merge_build_host: true

  {% set mpi_prefix = "mpi_" + mpi %}
  string: {{ mpi_prefix }}_py{{ python }}_h{{ PKG_HASH }}_{{ build }}
  {% set build_pin = mpi_prefix + '_*' %}

requirements:
  build:
  host:
    - python {{ python }}
    - git
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - cmake
    - sed
    - {{ mpi }}
    - {{ mpi }}-mpifort
    - {{ mpi }}-mpicc
    - {{ mpi }}-mpicxx
    - llvm-openmp
    - parmetis
    - metis
    - netcdf-fortran * {{ mpi_prefix }}_*
    - libgfortran5
  run:
    - python {{ python }}
    - {{ mpi }}
    - llvm-openmp
    - parmetis
    - metis
    - netcdf-fortran * {{ mpi_prefix }}_*
test:
  commands:
    - schism -v

about:
  home: https://github.com/schism-dev/schism
  license: Apache-2
  license_family: APACHE
  license_file: LICENSE
  summary: 'Semi-implicit Cross-scale Hydroscience Integrated System Model'

extra:
  recipe-maintainers:
    - brey
