name: documentation 
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: sudo add-apt-repository -y ppa:xtradeb/apps && sudo apt-get update && sudo apt-get install -y weasyprint chromium
      - run: pip install mkdocs-material mkdocs-with-pdf weasyprint
      - run: mkdocs gh-deploy --force
