name: documentation 
on:
  push:
    branches:
      - master
      - docs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - run: pip install mkdocs-material mkdocs-with-pdf
      - run: mkdocs gh-deploy --force
